name: Release

on:
  push:
    branches: [ master ]

jobs:
  tag:
    name: Tag repo
    runs-on: ubuntu-latest
    outputs:
      releaseNotes: ${{ steps.tag-version.outputs.changelog }}
      releaseType: ${{ steps.tag-version.outputs.release_type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - name: Bump version and push tag
        id: tag-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

      - name: Commit files
        if: ${{ steps.tag-version.outputs.release_type != '' }}
        run: |
          git config --local user.email "platform@basistheory.com"
          git config --local user.name "github-actions[bot]"
          echo "${{ steps.tag-version.outputs.changelog }}" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore(release): upating changelog ${{ steps.tag-version.outputs.new_tag }} [skip ci]" || echo "Nothing to update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.tag-version.outputs.release_type != '' }}
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          branch: ${{ github.ref }}

  release:
    name: Release
    needs:
      - tag
    runs-on: ubuntu-latest
    if: ${{ needs.tag.outputs.releaseType != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Write Release Notes
        run: echo "${{ needs.tag.outputs.releaseNotes }}" > /tmp/releaseNotes.txt

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          version: latest
          args: release --release-notes /tmp/releaseNotes.txt --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
